parameters:
  paths:
    - ./../
  exclude_files: ~
  layers:
    - name: Application
      collectors:
        - type: bool
          must:
            - type: className
              regex: TS\\Tournament\\Application\\.*
          must_not:
            - type: className
              regex: TS\\Tournament\\Application\\Dto
    - name: Domain
      collectors:
        - type: bool
          must:
            - type: className
              regex: TS\\Tournament\\Features\\.*
          must_not:
            - type: className
              regex: .*.Interface
            - type: className
              regex: .*.Dto
            - type: className
              regex: .*\\Entity\\.*

    - name: Infrastructure
      collectors:
        - type: className
          regex: TS\\Tournament\\Infrastructure\\.*

    - name: UI
      collectors:
        - type: className
          regex: Hub\\Tournament\\UI\\.*

  ruleset:
    UI:
      - Application
      - Infrastructure

    Application:
      - Domain
      - Infrastructure

    Domain: ~
    Infrastructure: ~