parameters:

services:
  TS\Components\Tournament\UI\Console\GenerateTournamentCommand:
    autowire: true

  TS\Components\Tournament\UI\Console\SimulateTournamentCommand:
    autowire: true

  TS\Components\Tournament\Infrastructure\Repository\Doctrine\TournamentRepository:
    autowire: true

  TS\Components\Tournament\Infrastructure\Repository\Doctrine\SimulateRepository:
    autowire: true

  TS\Components\Tournament\Infrastructure\Repository\Doctrine\MatchRepository:
    autowire: true

  TS\Components\Tournament\Infrastructure\Repository\InMemory\TeamsRepository:
    autowire: true

  TS\Components\Tournament\Features\Forecast\Generator\ForecastGeneratorByGoalDifference:
    autowire: true

  TS\Components\Tournament\Features\Forecast\Generator\ForecastGeneratorByGoalAverage:
    autowire: true

  TS\Components\Tournament\Infrastructure\Dao\ForecastDao:
    arguments:
      - '@doctrine.dbal.default_connection'

  TS\Components\Tournament\Features\Forecast\Generator\ForecastGeneratorInterface: '@TS\Components\Tournament\Features\Forecast\Generator\ForecastGeneratorByGoalDifference'
  TS\Components\Tournament\Features\Simulate\MatchRepositoryInterface: '@TS\Components\Tournament\Infrastructure\Repository\Doctrine\MatchRepository'
  TS\Components\Tournament\Features\Simulate\SimulateRepositoryInterface: '@TS\Components\Tournament\Infrastructure\Repository\Doctrine\SimulateRepository'
  TS\Components\Tournament\Features\Generate\TournamentRepositoryInterface: '@TS\Components\Tournament\Infrastructure\Repository\Doctrine\TournamentRepository'
  TS\Components\Tournament\Features\Teams\TeamsRepositoryInterface: '@TS\Components\Tournament\Infrastructure\Repository\InMemory\TeamsRepository'

  TS\Components\Tournament\Features\Forecast\ForecastDaoInterface: '@TS\Components\Tournament\Infrastructure\Dao\ForecastDao'
